file_format: "1"
id: generic_4x6_split
name: ushio_split48
type: shield
url: https://example.com
requires: [seeeduino_xiao]
exposes: []
features:
  - keys
siblings:
  - generic_4x6_split_left
  - generic_4x6_split_right